# -*- coding: utf-8 -*-
"""Hass6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zer9W6IKRHaXBo3lcasszuCt-BOGoWd0
"""

class CalculateEmission:
  def __init__(self,estimated_attance,student,non_student):
    self.mean_attance = (estimated_attance[0]+estimated_attance[1])//2
    self.student_percent = student
    self.non_student_percent = non_student
    self.train_percent_student = 0.05
    self.train_percent_non_student = 0.03
    self.bike_percent_student = 0.6
    self.bike_percent_non_student = 0.3
    self.car_percent_student = 0.4
    self.car_percent_non_student = 0.6
    self.plane_percent_student = 0.01
    self.plane_percent_non_student = 0.05
    self.bus_percent_student = 0.04
    self.bus_percent_non_student = 0.02
    self.student_CI = [estimated_attance[0]*self.student_percent,estimated_attance[1]*self.non_student_percent]
    self.non_student_CI = [estimated_attance[0]*self.non_student_percent,estimated_attance[1]*self.student_percent]
    self.train_distance = 20
    self.car_distance = 10
    self.bike_distance = 5
    self.plane_distance = 350
    self.bus_distance = 15
    self.train_emiison = 0.056
    self.car_emission = 0.347
    self.plane_emission = 0.396
    self.bus_emissioin = 0.177
    self.bike_emission = 0

  def calculate_emission(self):

    student_emission = [self.train_distance*self.train_emiison*self.student_CI[0]+self.car_distance*self.car_emission*self.student_CI[0]
                        +self.bike_distance*self.bike_emission*self.student_CI[0]+self.plane_distance*self.plane_percent_student*self.student_CI[0]+

                        self.bus_distance*self.bus_emissioin*self.student_CI[0],

                        self.train_distance*self.train_emiison*self.student_CI[1]+self.car_distance*self.car_emission*self.student_CI[1]
                        +self.bike_distance*self.bike_emission*self.student_CI[1]+self.plane_distance*self.plane_percent_student*self.student_CI[1]+
                        self.bus_distance*self.bus_emissioin*self.student_CI[1]]

    non_student_emission = [self.train_distance*self.train_emiison*self.non_student_CI[0]+
                            self.car_distance*self.car_emission*self.non_student_CI[0]+
                            self.bike_distance*self.bike_emission*self.non_student_CI[0]+
                            self.plane_distance*self.plane_percent_non_student*self.non_student_CI[0]+
                            self.bus_distance*self.bus_emissioin*self.non_student_CI[0],

                            self.train_distance*self.train_emiison*self.non_student_CI[1]+
                            self.car_distance*self.car_emission*self.non_student_CI[1]+
                            self.bike_distance*self.bike_emission*self.non_student_CI[1]
                            + self.plane_distance*self.plane_percent_non_student*self.non_student_CI[1]+
                            self.bus_distance*self.bus_emissioin*self.non_student_CI[1]]
    return student_emission,non_student_emission



