# -*- coding: utf-8 -*-
"""smbelectricityrateplan

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H-Wr0CuD4_ZVG7rN7aGWhrL9yBNDbkdV
"""

from scipy.optimize import minimize
from scipy.optimize import Bounds
import pandas as pd

from sectors.smbsector import SMBSector

class SMBElectricityRatePlan:
    def __init__(self, file_path, sheet_name, usage_data):
        self.df = pd.read_excel(file_path, sheet_name=sheet_name)
        self.usage_data = usage_data
        self.parameters = {}
        self.load_parameters()

    def get_parameter(self, sector, plan, season, ptype, phase=None, column='Energy Rate'):
        query = f"Sector == '{sector}' and Plan == '{plan}' and Season == '{season}' and Type == '{ptype}'"
        if phase:
            query += f" and Phase == '{phase}'"
        return self.df.query(query)[column].values[0]

    def load_parameters(self):
        # Load all required parameters
        self.parameters['A1NTBS'] = self.get_parameter('Small and Medium Business', 'A-1', 'Summer', 'Non-TOU')
        self.parameters['A1NTBW'] = self.get_parameter('Small and Medium Business', 'A-1', 'Winter', 'Non-TOU')
        self.parameters['A1NTB_polyprice'] = self.get_parameter('Small and Medium Business', 'A-1', 'Non-TOU', phase='Poly', column='Customer Charge Rate')
        self.parameters['A1NTB_singleprice'] = self.get_parameter('Small and Medium Business', 'A-1', 'Non-TOU', phase='Single', column='Customer Charge Rate')
        self.parameters['A1BSpeakprice'] = self.get_parameter('Small and Medium Business', 'A-1', 'Summer', 'Peak')
        self.parameters['A1BSpartpeakprice'] = self.get_parameter('Small and Medium Business', 'A-1', 'Summer', 'Part-Peak')
        self.parameters['A1BSoffpeakprice'] = self.get_parameter('Small and Medium Business', 'A-1', 'Summer', 'Off-Peak')
        self.parameters['A1BWpartpeakprice'] = self.get_parameter('Small and Medium Business', 'A-1', 'Winter', 'Part-Peak')
        self.parameters['A1BWoffpeakprice'] = self.get_parameter('Small and Medium Business', 'A-1', 'Winter', 'Off-Peak')
        self.parameters['A1B_polyprice'] = self.get_parameter('Small and Medium Business', 'A-1', 'Peak', phase='Poly', column='Customer Charge Rate')
        self.parameters['A1B_singleprice'] = self.get_parameter('Small and Medium Business', 'A-1', 'Peak', phase='Single', column='Customer Charge Rate')
        self.parameters['B1BSpeakprice'] = self.get_parameter('Small and Medium Business', 'B-1', 'Summer', 'Peak')
        self.parameters['B1BSpartpeakprice'] = self.get_parameter('Small and Medium Business', 'B-1', 'Summer', 'Part-Peak')
        self.parameters['B1BSoffpeakprice'] = self.get_parameter('Small and Medium Business', 'B-1', 'Summer', 'Off-Peak')
        self.parameters['B1BWpeakprice'] = self.get_parameter('Small and Medium Business', 'B-1', 'Winter', 'Peak')
        self.parameters['B1BWsuperoffpeakprice'] = self.get_parameter('Small and Medium Business', 'B-1', 'Winter', 'Super-Off-Peak')
        self.parameters['B1BWoffpeakprice'] = self.get_parameter('Small and Medium Business', 'B-1', 'Winter', 'Off-Peak')
        self.parameters['B1B_polyprice'] = self.get_parameter('Small and Medium Business', 'B-1', 'Peak', phase='Poly', column='Customer Charge Rate')
        self.parameters['B1B_singleprice'] = self.get_parameter('Small and Medium Business', 'B-1', 'Peak', phase='Single', column='Customer Charge Rate')
        self.parameters['B1STBSpeakprice'] = self.get_parameter('Small and Medium Business', 'B-1-ST', 'Summer', 'Peak')
        self.parameters['B1STBSpartpeakprice'] = self.get_parameter('Small and Medium Business', 'B-1-ST', 'Summer', 'Part-Peak')
        self.parameters['B1STBSoffpeakprice'] = self.get_parameter('Small and Medium Business', 'B-1-ST', 'Summer', 'Off-Peak')
        self.parameters['B1STBWpeakprice'] = self.get_parameter('Small and Medium Business', 'B-1-ST', 'Winter', 'Peak')
        self.parameters['B1STBWpartpeakprice'] = self.get_parameter('Small and Medium Business', 'B-1-ST', 'Winter', 'Part-Peak')
        self.parameters['B1STBWsuperoffpeakprice'] = self.get_parameter('Small and Medium Business', 'B-1-ST', 'Winter', 'Super-Off-Peak')
        self.parameters['B1STBWoffpeakprice'] = self.get_parameter('Small and Medium Business', 'B-1-ST', 'Winter', 'Off-Peak')
        self.parameters['B1STB_polyprice'] = self.get_parameter('Small and Medium Business', 'B-1-ST', 'Peak', phase='Poly', column='Customer Charge Rate')
        self.parameters['B1STB_singleprice'] = self.get_parameter('Small and Medium Business', 'B-1-ST', 'Peak', phase='Single', column='Customer Charge Rate')
        self.parameters['B1STB_demand_rate'] = 8.25
        self.parameters['B6BSpeakprice'] = self.get_parameter('Small and Medium Business', 'B-6', 'Summer', 'Peak')
        self.parameters['B6BSoffpeakprice'] = self.get_parameter('Small and Medium Business', 'B-6', 'Summer', 'Off-Peak')
        self.parameters['B6BWpeakprice'] = self.get_parameter('Small and Medium Business', 'B-6', 'Winter', 'Peak')
        self.parameters['B6BWsuperoffpeakprice'] = self.get_parameter('Small and Medium Business', 'B-6', 'Winter', 'Super-Off-Peak')
        self.parameters['B6BWoffpeakprice'] = self.get_parameter('Small and Medium Business', 'B-6', 'Winter', 'Off-Peak')
        self.parameters['B6B_polyprice'] = self.get_parameter('Small and Medium Business', 'B-6', 'Peak', phase='Poly', column='Customer Charge Rate')
        self.parameters['B6B_singleprice'] = self.get_parameter('Small and Medium Business', 'B-6', 'Peak', phase='Single', column='Customer Charge Rate')
        self.parameters['B10SVBSpeakprice'] = self.get_parameter('Small and Medium Business', 'B-10_SV', 'Summer', 'Peak')
        self.parameters['B10SVBSpartpeakprice'] = self.get_parameter('Small and Medium Business', 'B-10_SV', 'Summer', 'Part-Peak')
        self.parameters['B10SVBSoffpeakprice'] = self.get_parameter('Small and Medium Business', 'B-10_SV', 'Summer', 'Off-Peak')
        self.parameters['B10SVBWpeakprice'] = self.get_parameter('Small and Medium Business', 'B-10_SV', 'Winter', 'Peak')
        self.parameters['B10SVBWsuperoffpeakprice'] = self.get_parameter('Small and Medium Business', 'B-10_SV', 'Winter', 'Super-Off-Peak')
        self.parameters['B10SVBWoffpeakprice'] = self.get_parameter('Small and Medium Business', 'B-10_SV', 'Winter', 'Off-Peak')
        self.parameters['B10SVB_Customer_Charge'] = self.get_parameter('Small and Medium Business', 'B-10_SV', 'Summer', 'Peak', column='Customer Charge Rate')
        self.parameters['B10SVB_demand_rate'] = 21.87
        self.parameters['B10PVBSpeakprice'] = self.get_parameter('Small and Medium Business', 'B-10_PV', 'Summer', 'Peak')
        self.parameters['B10PVBSpartpeakprice'] = self.get_parameter('Small and Medium Business', 'B-10_PV', 'Summer', 'Part-Peak')
        self.parameters['B10PVBSoffpeakprice'] = self.get_parameter('Small and Medium Business', 'B-10_PV', 'Summer', 'Off-Peak')
        self.parameters['B10PVBWpeakprice'] = self.get_parameter('Small and Medium Business', 'B-10_PV', 'Winter', 'Peak')
        self.parameters['B10PVBWsuperoffpeakprice'] = self.get_parameter('Small and Medium Business', 'B-10_PV', 'Winter', 'Super-Off-Peak')
        self.parameters['B10PVBWoffpeakprice'] = self.get_parameter('Small and Medium Business', 'B-10_PV', 'Winter', 'Off-Peak')
        self.parameters['B10PVB_Customer_Charge'] = self.get_parameter('Small and Medium Business', 'B-10_PV', 'Summer', 'Peak', column='Customer Charge Rate')
        self.parameters['B10PVB_demand_rate'] = 21.16
        self.parameters['B10TVBSpeakprice'] = self.get_parameter('Small and Medium Business', 'B-10_TV', 'Summer', 'Peak')
        self.parameters['B10TVBSpartpeakprice'] = self.get_parameter('Small and Medium Business', 'B-10_TV', 'Summer', 'Part-Peak')
        self.parameters['B10TVBSoffpeakprice'] = self.get_parameter('Small and Medium Business', 'B-10_TV', 'Summer', 'Off-Peak')
        self.parameters['B10TVBWpeakprice'] = self.get_parameter('Small and Medium Business', 'B-10_TV', 'Winter', 'Peak')
        self.parameters['B10TVBWsuperoffpeakprice'] = self.get_parameter('Small and Medium Business', 'B-10_TV', 'Winter', 'Super-Off-Peak')
        self.parameters['B10TVBWoffpeakprice'] = self.get_parameter('Small and Medium Business', 'B-10_TV', 'Winter', 'Off-Peak')
        self.parameters['B10TVB_Customer_Charge'] = self.get_parameter('Small and Medium Business', 'B-10_TV', 'Summer', 'Peak', column='Customer Charge Rate')
        self.parameters['B10TVB_demand_rate'] = 14.46

    def objective(self, x):
        A1NTB, A1B, B1B, B1STB, B6B, B10SVB, B10PVB, B10TVB, A1NTB_poly, A1NTB_single, A1B_poly, A1B_single, B1B_poly, B1B_single, B1STB_poly, B1STB_single, B6B_poly, B6B_single = x
        usage_data = self.usage_data
        meter_input, time_in_use, max_15min_usage, B1STB_highest_demand_15mins = usage_data['meter_input'], usage_data['time_in_use'], usage_data['max_15min_usage'], usage_data['B1STB_highest_demand_15mins']

        A1NTBprice = (self.parameters['A1NTBS'] * usage_data['A1NTBStotal_usage'] +
                      self.parameters['A1NTBW'] * usage_data['A1NTBWtotal_usage'] +
                      (self.parameters['A1NTB_polyprice'] * A1NTB_poly + self.parameters['A1NTB_singleprice'] * A1NTB_single) * meter_input * time_in_use)
        A1BSprice = (self.parameters['A1BSpeakprice'] * usage_data['A1BSpeak_usage'] +
                     self.parameters['A1BSpartpeakprice'] * usage_data['A1BSpartpeak_usage'] +
                     self.parameters['A1BSoffpeakprice'] * usage_data['A1BSoffpeak_usage'])
        A1BWprice = (self.parameters['A1BWpartpeakprice'] * usage_data['A1BWpartpeak_usage'] +
                     self.parameters['A1BWoffpeakprice'] * usage_data['A1BWoffpeak_usage'])
        A1Bprice = A1BSprice + A1BWprice + (self.parameters['A1B_polyprice'] * A1B_poly + self.parameters['A1B_singleprice'] * A1B_single) * meter_input * time_in_use

        B1BSprice = (self.parameters['B1BSpeakprice'] * usage_data['B1BSpeak_usage'] +
                     self.parameters['B1BSpartpeakprice'] * usage_data['B1BSpartpeak_usage'] +
                     self.parameters['B1BSoffpeakprice'] * usage_data['B1BSoffpeak_usage'])
        B1BWprice = (self.parameters['B1BWpeakprice'] * usage_data['B1BWpeak_usage'] +
                     self.parameters['B1BWsuperoffpeakprice'] * usage_data['B1BWsuperoffpeak_usage'] +
                     self.parameters['B1BWoffpeakprice'] * usage_data['B1BWoffpeak_usage'])
        B1Bprice = B1BSprice + B1BWprice + (self.parameters['B1B_polyprice'] * B1B_poly + self.parameters['B1B_singleprice'] * B1B_single) * meter_input * time_in_use

        B1STBSprice = (self.parameters['B1STBSpeakprice'] * usage_data['B1STBSpeak_usage'] +
                       self.parameters['B1STBSpartpeakprice'] * usage_data['B1STBSpartpeak_usage'] +
                       self.parameters['B1STBSoffpeakprice'] * usage_data['B1STBSoffpeak_usage'])
        B1STBWprice = (self.parameters['B1STBWpeakprice'] * usage_data['B1STBWpeak_usage'] +
                       self.parameters['B1STBWpartpeakprice'] * usage_data['B1STBWpartpeak_usage'] +
                       self.parameters['B1STBWsuperoffpeakprice'] * usage_data['B1STBWsuperoffpeak_usage'] +
                       self.parameters['B1STBWoffpeakprice'] * usage_data['B1STBWoffpeak_usage'])
        B1STBprice = B1STBSprice + B1STBWprice + (self.parameters['B1STB_polyprice'] * B1STB_poly + self.parameters['B1STB_singleprice'] * B1STB_single) * meter_input * time_in_use + self.parameters['B1STB_demand_rate'] * B1STB_highest_demand_15mins

        B6BSprice = (self.parameters['B6BSpeakprice'] * usage_data['B6BSpeak_usage'] +
                     self.parameters['B6BSoffpeakprice'] * usage_data['B6BSoffpeak_usage'])
        B6BWprice = (self.parameters['B6BWpeakprice'] * usage_data['B6BWpeak_usage'] +
                     self.parameters['B6BWsuperoffpeakprice'] * usage_data['B6BWsuperoffpeak_usage'] +
                     self.parameters['B6BWoffpeakprice'] * usage_data['B6BWoffpeak_usage'])
        B6Bprice = B6BSprice + B6BWprice + (self.parameters['B6B_polyprice'] * B6B_poly + self.parameters['B6B_singleprice'] * B6B_single) * meter_input * time_in_use

        B10SVBSprice = (self.parameters['B10SVBSpeakprice'] * usage_data['B10SVBSpeak_usage'] +
                        self.parameters['B10SVBSpartpeakprice'] * usage_data['B10SVBSpartpeak_usage'] +
                        self.parameters['B10SVBSoffpeakprice'] * usage_data['B10SVBSoffpeak_usage'])
        B10SVBWprice = (self.parameters['B10SVBWpeakprice'] * usage_data['B10SVBWpeak_usage'] +
                        self.parameters['B10SVBWsuperoffpeakprice'] * usage_data['B10SVBWsuperoffpeak_usage'] +
                        self.parameters['B10SVBWoffpeakprice'] * usage_data['B10SVBWoffpeak_usage'])
        B10SVBprice = B10SVBSprice + B10SVBWprice + self.parameters['B10SVB_Customer_Charge'] * meter_input * time_in_use + self.parameters['B10SVB_demand_rate'] * max_15min_usage

        B10PVBSprice = (self.parameters['B10PVBSpeakprice'] * usage_data['B10PVBSpeak_usage'] +
                        self.parameters['B10PVBSpartpeakprice'] * usage_data['B10PVBSpartpeak_usage'] +
                        self.parameters['B10PVBSoffpeakprice'] * usage_data['B10PVBSoffpeak_usage'])
        B10PVBWprice = (self.parameters['B10PVBWpeakprice'] * usage_data['B10PVBWpeak_usage'] +
                        self.parameters['B10PVBWsuperoffpeakprice'] * usage_data['B10PVBWsuperoffpeak_usage'] +
                        self.parameters['B10PVBWoffpeakprice'] * usage_data['B10PVBWoffpeak_usage'])
        B10PVBprice = B10PVBSprice + B10PVBWprice + self.parameters['B10PVB_Customer_Charge'] * meter_input * time_in_use + self.parameters['B10PVB_demand_rate'] * max_15min_usage

        B10TVBSprice = (self.parameters['B10TVBSpeakprice'] * usage_data['B10TVBSpeak_usage'] +
                        self.parameters['B10TVBSpartpeakprice'] * usage_data['B10TVBSpartpeak_usage'] +
                        self.parameters['B10TVBSoffpeakprice'] * usage_data['B10TVBSoffpeak_usage'])
        B10TVBWprice = (self.parameters['B10TVBWpeakprice'] * usage_data['B10TVBWpeak_usage'] +
                        self.parameters['B10TVBWsuperoffpeakprice'] * usage_data['B10TVBWsuperoffpeak_usage'] +
                        self.parameters['B10TVBWoffpeakprice'] * usage_data['B10TVBWoffpeak_usage'])
        B10TVBprice = B10TVBSprice + B10TVBWprice + self.parameters['B10TVB_Customer_Charge'] * meter_input * time_in_use + self.parameters['B10TVB_demand_rate'] * max_15min_usage

        return (A1NTBprice * A1NTB + A1Bprice * A1B + B1Bprice * B1B + B1STBprice * B1STB +
                B6Bprice * B6B + B10SVBprice * B10SVB + B10PVBprice * B10PVB + B10TVBprice * B10TVB)

    def optimize(self):
     objective = lambda x: self.objective(x)
     constraints = [
        {'type': 'eq', 'fun': lambda x: x[0] + x[1] + x[2] + x[3] + x[4] + x[5] + x[6] + x[7] - 1},
        {'type': 'eq', 'fun': lambda x: x[5] + x[6] + x[7] - x[4]},
        {'type': 'eq', 'fun': lambda x: x[8] + x[9] - 1},  # A1NTB poly + single
        {'type': 'eq', 'fun': lambda x: x[10] + x[11] - 1},  # A1B poly + single
        {'type': 'eq', 'fun': lambda x: x[12] + x[13] - 1},  # B1B poly + single
        {'type': 'eq', 'fun': lambda x: x[14] + x[15] - 1},  # B1STB poly + single
        {'type': 'eq', 'fun': lambda x: x[16] + x[17] - 1},  # B6B poly + single
     ]
     bounds = Bounds([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
     x0 = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

     result = minimize(objective, x0, method='SLSQP', constraints=constraints, bounds=bounds)

    # Round results to enforce binary constraints
     x_opt = [round(xi) for xi in result.x]
     obj_val = self.objective(x_opt)

     return {'x': x_opt, 'objective': obj_val}

