import { Company } from './company.model'; 

export const companies: Company[] = [
  {
    name: 'Adidas',
    description: "Running shoes, sports t-shirts ",
    revenue: 200,
    savings: 100,
    current_emissions: 500,
    emissions_avoided: 100,
    industry_type: "banking",
    industry_sector: "harvesting natural resources",
    lat: 37.7749,
    lng: -122.4194,
    logo: 'assets/Adidas-logo.png',
    actions: [
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 50 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 20 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 40 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 70 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 90 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 40 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 30 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 10 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 50 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 20 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 40 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 70 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 90 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 40 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 30 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 10 },
    ]
  },
  {
    name: 'Colgate',
    description: "Toothpaste",
    revenue: 500,
    savings: 200,
    current_emissions: 300,
    emissions_avoided: 200,
    industry_type: "banking",
    industry_sector: "harvesting natural resources",
    lat: 34.0522,
    lng: -118.2437,
    logo: 'assets/Colgate-logo.png',
    actions: [
      { name: 'Recycling', description: 'Plastic recycling', date: '5/3/2023', percentageComplete: 25 },
      { name: 'Recycling', description: 'Plastic recycling', date: '5/3/2023', percentageComplete: 65 },
      { name: 'Recycling', description: 'Plastic recycling', date: '5/3/2023', percentageComplete: 95 },
      { name: 'Recycling', description: 'Plastic recycling', date: '5/3/2023', percentageComplete: 75 },
      { name: 'Recycling', description: 'Plastic recycling', date: '5/3/2023', percentageComplete: 100 },
      { name: 'Recycling', description: 'Plastic recycling', date: '5/3/2023', percentageComplete: 10 },
      { name: 'Recycling', description: 'Plastic recycling', date: '5/3/2023', percentageComplete: 35 },
      { name: 'Recycling', description: 'Plastic recycling', date: '5/3/2023', percentageComplete: 95 },
      { name: 'Recycling', description: 'Plastic recycling', date: '5/3/2023', percentageComplete: 75 },
    ]
  },
  {
    name: 'CVS_Health',
    description: "Running shoes, sports t-shirts ",
    revenue: 200,
    savings: 100,
    current_emissions: 500,
    emissions_avoided: 100,
    industry_type: "banking",
    industry_sector: "harvesting natural resources",
    lat: 37.7749,
    lng: -122.4194,
    logo: 'assets/CVS_Health-logo.png',
    actions: [
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 50 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 20 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 40 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 70 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 90 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 40 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 30 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 10 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 50 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 20 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 40 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 70 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 90 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 40 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 30 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 10 },
    ]
  },
  {
    name: 'AG-Barr',
    description: "Running shoes, sports t-shirts ",
    revenue: 200,
    savings: 100,
    current_emissions: 500,
    emissions_avoided: 100,
    industry_type: "banking",
    industry_sector: "harvesting natural resources",
    lat: 37.7749,
    lng: -122.4194,
    logo: 'assets/AG-Barr-logo.png',
    actions: [
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 50 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 20 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 40 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 70 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 90 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 40 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 30 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 10 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 50 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 20 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 40 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 70 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 90 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 40 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 30 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 10 },
    ]
  },
  {
    name: 'Davita',
    description: "Running shoes, sports t-shirts ",
    revenue: 200,
    savings: 100,
    current_emissions: 500,
    emissions_avoided: 100,
    industry_type: "banking",
    industry_sector: "harvesting natural resources",
    lat: 37.7749,
    lng: -122.4194,
    logo: 'assets/Davita-logo.png',
    actions: [
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 50 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 20 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 40 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 70 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 90 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 40 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 30 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 10 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 50 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 20 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 40 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 70 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 90 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 40 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 30 },
      { name: 'Composting', description: 'Employees composting', date: '1/1/2024', percentageComplete: 10 },
    ]
  }
];
