"""
This data appears to be a categorization of various food items into different waste and food type categories.
The main structure is a dictionary or object called food_waste_category with several key categories:

"Food Waste non meat": This is the largest category, containing a wide variety of non-meat food items
                       including fruits, vegetables, grains, baked goods, sauces, and other plant-based foods.
"Food Waste meat only": This category contains meat and fish products.
"Beef": Specific beef products.
"Poultry": Chicken and turkey products.
"Grains": Various whole grains and grain products.
"Bread": Different types of bread and bread-like products.
"Fruits and Vegetables": A comprehensive list of fruits and vegetables, including some processed forms
                         (like canned or dried).
"Dairy Products": This category seems to include not just dairy products, but also items that often contain dairy,
                  like pastries and some sauces.

The categorization appears to be based on:

1. The primary ingredient or food type (e.g., meat vs. non-meat)
2. The specific type of food (e.g., grains, fruits and vegetables)
3. The potential for waste in different categories

It's worth noting that some items appear in multiple categories. For example, some items in the "Dairy Products"
category also appear in "Food Waste non meat", suggesting that these categories are not mutually exclusive
but rather serve different classification purposes.
"""


food_waste_category = {
  "Food Waste non meat": [
    "Aioli sauce (garlic and olive oil mayonnaise), prepacked",
    "Alfalfa seeds, sprouted, raw",
    "Almond, (with peel)",
    "Amaranth, raw",
    "American-style sauce, prepacked",
    "Apple pie with custard (flour, eggs, cream, sugar, apple alcohol)",
    "Apple tart",
    "Apple, Canada, pulp, raw",
    "Apples, raw, without skin, cooked, boiled/cooked in water",
    "Aromatic stock cube, for fish, dehydrated",
    "Artichoke base, canned, drained",
    "Asian noodles, flavoured, cooked",
    "Avocado oil",
    "Avocado, pulp, raw",
    "Baby food jar with vegetables and starch, from 4-6 months",
    "Baking powder or raising agent",
    "Baklava (oriental pastry with almonds and syrup)",
    "Banana, pulp, dried",
    "Barley flour",
    "Barley, whole, raw",
    "Basil, dried",
    "Basque-style sauce or tomato sauce with sweet peppers, prepacked",
    "Bay, leaves",
    "Beans, mung, mature, seeds, dry",
    "Beer, dark",
    "Biscuit (cookie) filled with fruit paste or fruit puree",
    "Biscuit (cookie) with nuts (no chocolate or lightly chocolate-flavoured)",
    "Biscuit (cookie), assortment of miniature sweets and biscuits",
    "Black pepper, powder",
    "Blinis",
    "Breakfast cereals, mix of puffed or extruded cereals, fortified with vitamins and chemical elements",
    "Bran grain bread",
    "Brioche",
    "Broccoli, raw",
    "Butter biscuit (cookie)",
    "Cane molasses",
    "Caramelized custard cream (crème brûlée), refrigerated",
    "Carbonara sauce (cream sauce with lardoons), prepacked",
    "Cardamom, powder",
    "Carrot, raw",
    "Cauliflower, raw",
    "Celery salt",
    "Champagne",
    "Cheese sauce for risotto or pasta, prepacked",
    "Chick pea flour",
    "Chicory, raw",
    "Chili pepper, raw",
    "Chinese cabbage (nappa cabbage or bok choy), cooked",
    "Chive or spring onion, fresh",
    "Chocolate sauce",
    "Christmas brioche with candied fruits, prepacked",
    "Cider",
    "Cider, dry",
    "Cider, sweet",
    "Cloves",
    "Cocoa powder, without sugar, powder, instant, non rehydrated",
    "Coconut milk or coconut cream",
    "Coffee, ground",
    "Cola, with sugar and without caffeine",
    "Combined oil (blended vegetable oils)",
    "Cone, wafer for ice cream",
    "Coriander, fresh",
    "Corn chips or tortilla chips",
    "Cos or romaine lettuce, raw",
    "Cranberry, raw",
    "Cream sauce",
    "Cream sauce with mushrooms, prepacked",
    "Croutons",
    "Cucumber, pulp and peel, raw",
    "Cumin, seed",
    "Curly endive, raw",
    "Curly kale, cooked",
    "Curry, powder",
    "Custard dessert, coffee, refrigerated",
    "Dark chocolate bar, filled with praline",
    "Dark chocolate bar, with fruits (orange, raspberries, pear)",
    "Dark chocolate bar, without sugar and with artificial sweeteners",
    "Diced mixed vegetables, canned, drained",
    "Dill, fresh",
    "Doughnut, plain",
    "Dried pasta, gluten-free, cooked, unsalted",
    "Dried pasta, wholemeal, cooked, unsalted",
    "Eggplant, raw",
    "Escaroles",
    "Falafel",
    "Fennel, boiled/cooked in water",
    "Fennel, raw",
    "Flaxseed",
    "Flaxseed, brown",
    "Fresh cream cheese cake",
    "Garlic, fresh",
    "Gelatine, dried",
    "Ginger, powder",
    "Gingerbread",
    "Grand veneur sauce (a reduction of red wine with garlic, shallots and red currant jelly), prepacked",
    "Grape, raw",
    "Grape, red, raw",
    "Grated carrots",
    "Green pepper sauce, prepacked",
    "Grissini or bread stick",
    "Honey",
    "Hunter-style sauce (a garnish of mushrooms, shallots and tomatoes in white wine sauce), prepacked",
    "Iceberg lettuce, raw",
    "Indian-style sauce, tandoori or garam masala type, prepacked",
    "Jam, apricot",
    "Jam, raspberry",
    "Jam, strawberry",
    "Ketchup",
    "Kir (Cocktail of white wine with red fruit liqueur)",
    "Kiwi fruit, pulp and seeds, raw",
    "Lemon juice, pure juice",
    "Lemon or lime base, for beverage, without sugar (to be diluted)",
    "Lemon tart",
    "Lemon, pulp, raw",
    "Lentil, blond, cooked",
    "Lentil, cooked",
    "Lettuce, raw",
    "Light custard cream with vanilla, prepacked",
    "Light syrup for canned fruits in syrup",
    "Lime, pulp, raw",
    "Liquid cream 30% fat, UHT",
    "Macaroon",
    "Maize/corn starch",
    "Mango, pulp, raw (Brazil by plane)",
    "Mayonnaise (70% fat and more)",
    "Mayonnaise flavoured with garlic, chilli pepper and fish broth, prepacked",
    "Meal replacement low calorie, in powder, reconstituted with skimmed milk, milkshake type",
    "Melon, cantaloupe (ex Cavaillon or Charentais melon), pulp, raw",
    "Meringue",
    "Mesclun or salads, mix of baby leaves",
    "Mint, fresh",
    "Miso",
    "Mix of 4 spices",
    "Molokhia powder (dried jute leaves)",
    "Mustard",
    "Nutritional yeast",
    "Oat flakes, boiled/cooked in water",
    "Oat, raw",
    "Olive oil, extra virgin",
    "Onion, raw",
    "Orange juice, home-made",
    "Orange, pulp, raw",
    "Paëlla",
    "Papaya, pulp, raw",
    "Paprika",
    "Parsley, dried",
    "Parsley, fresh",
    "Pastis (anise-flavoured spirit)",
    "Peanut",
    "Peanut butter or peanut paste",
    "Pear, canned in light syrup, not drained",
    "Pecan nut",
    "Persimmon, pulp, raw",
    "Phyllo or filo dough, raw",
    "Pine nuts",
    "Pineapple, in light syrup, canned, drained",
    "Plant-based sausage with tofu (vegan)",
    "Plantain banana, cooked",
    "Pomegranate, pulp and pips, raw",
    "Pop-corn or oil popped maize, salted",
    "Poppy, seed",
    "Prawn crackers",
    "Puffed rice textured bread, wholemeal",
    "Quinoa, raw",
    "Radish, raw",
    "Raisin",
    "Red cabbage, raw",
    "Red kuri squash, pulp, raw",
    "Red wine sauce",
    "Rice bran",
    "Rice flour",
    "Rice noodle, cooked, unsalted",
    "Rice, mix of species (white, wholegrain, wild, red,etc.), raw",
    "Rice, raw",
    "Riste (Eggplant, tomatoes, onions)",
    "Rock-shaped coconut cake",
    "Rosemary, dried",
    "Rosemary, fresh",
    "Rostis or Potatoes cake",
    "Rum",
    "Rusk",
    "Rusk with eggs, sliced, prepacked",
    "Rye, whole, raw",
    "Saffron",
    "Sage, dried",
    "Salad dressing, (50-75% of oil), prepacked",
    "Salt, white, for human consumption (sea, igneous or rock), no enrichment",
    "Salty snacks, mini pretzels or sticks",
    "Sauce, butter, prepacked",
    "Sea lettuce (Enteromorpha sp.), dried or dehydrated",
    "Sea salt, grey, no enrichment",
    "Seitan",
    "Sesame oil",
    "Sesame seed",
    "Shallot, raw",
    "Shortbread cookie with fruit (apple, red berries, etc.)",
    "Snow pea, boiled/cooked in water",
    "Soft-ripened cheese, triple cream, around 40% fat",
    "Soup, pistou (basil, garlic and olive oil), dehydrated and reconstituted",
    "Soy \"cream\" preparation",
    "Soy sauce, prepacked",
    "Spinach, raw",
    "Spring roll",
    "Spring vegetables, frozen, raw (French beans, carrots, potatoes, green peas, onions)",
    "Strawberries tart",
    "Stuffed tomatoes",
    "Sugar, brown",
    "Sweet corn, canned, drained",
    "Sweet pepper, green, cooked",
    "Sweet potato, raw",
   

 "Swiss chard, raw",
    "Syrup, agave",
    "Syrup, maple",
    "Tahini (sesame paste)",
    "Tamarind, mature fruit, pulp, raw",
    "Tapenade (a puree of capers, pitted black olives, anchovy and herbs, with olive oil and lemon juice)",
    "Tempeh",
    "Thyme, dried",
    "Thyme, fresh",
    "Tomato paste, concentrated, canned",
    "Tomato pulp, canned",
    "Tomato sauce, w olives, prepacked",
    "Tomato sauce, w vegetables, prepacked",
    "Tomato sauce, with onions, prepacked",
    "Tomato, cherry, raw",
    "Tomato, dried",
    "Tomato, raw",
    "Turmeric, powder",
    "Vinegar",
    "Walnut, dried, husked",
    "Water, bottled",
    "Watermelon, pulp, raw",
    "White pepper, powder",
    "Wild rice, raw",
    "Wine, red",
    "Wine, white, sparkling",
    "Yogurt cake",
    "Yogurt, goat's milk, plain, around 5% fat"
  ],
  "Food Waste meat only": [
    "Anchovy, fillets, rolled with capers, semi-preserved, drained",
    "Bacon, back",
    "Beef on skewer",
    "Beef, minced steak, 10% fat, cooked",
    "Bresaola",
    "Chicken cooked ham, in slices",
    "Cod, steamed",
    "Coppa",
    "Game Pâté",
    "Ham, in a pastry crusty",
    "Heart, turkey, cooked",
    "Mortadella with pistachios, pure pork",
    "Rillettes, salmon",
    "Salmon, smoked",
    "Turkey fat"
  ],
  "Beef": [
    "Beef on skewer",
    "Beef, minced steak, 10% fat, cooked",
    "Bresaola"
  ],
  "Poultry": [
    "Chicken cooked ham, in slices",
    "Heart, turkey, cooked",
    "Turkey fat"
  ],
  "Grains": [
    "Barley flour",
    "Barley, whole, raw",
    "Rye, whole, raw",
    "Oat flakes, boiled/cooked in water",
    "Oat, raw",
    "Wild rice, raw",
    "Rice, mix of species (white, wholegrain, wild, red,etc.), raw",
    "Rice, raw",
    "Quinoa, raw"
  ],
  "Bread": [
    "Bran grain bread",
    "Bagel",
    "Rusk",
    "Rusk with eggs, sliced, prepacked",
    "Grissini or bread stick",
    "Croutons"
  ],
  "Fruits and Vegetables": [
    "Apple, Canada, pulp, raw",
    "Apples, raw, without skin, cooked, boiled/cooked in water",
    "Artichoke base, canned, drained",
    "Avocado, pulp, raw",
    "Banana, pulp, dried",
    "Broccoli, raw",
    "Carrot, raw",
    "Cauliflower, raw",
    "Chinese cabbage (nappa cabbage or bok choy), cooked",
    "Chicory, raw",
    "Chive or spring onion, fresh",
    "Cranberry, raw",
    "Cucumber, pulp and peel, raw",
    "Curly endive, raw",
    "Curly kale, cooked",
    "Diced mixed vegetables, canned, drained",
    "Eggplant, raw",
    "Escaroles",
    "Fennel, boiled/cooked in water",
    "Fennel, raw",
    "Flaxseed",
    "Flaxseed, brown",
    "Grated carrots",
    "Grape, raw",
    "Grape, red, raw",
    "Green pepper sauce, prepacked",
    "Honey",
    "Iceberg lettuce, raw",
    "Kiwi fruit, pulp and seeds, raw",
    "Lemon juice, pure juice",
    "Lemon, pulp, raw",
    "Lentil, blond, cooked",
    "Lentil, cooked",
    "Lettuce, raw",
    "Lime, pulp, raw",
    "Macadamia nut",
    "Mango, pulp, raw (Brazil by plane)",
    "Melon, cantaloupe (ex Cavaillon or Charentais melon), pulp, raw",
    "Mesclun or salads, mix of baby leaves",
    "Mint, fresh",
    "Molokhia powder (dried jute leaves)",
    "Orange juice, home-made",
    "Orange, pulp, raw",
    "Papaya, pulp, raw",
    "Parsley, fresh",
    "Peanut",
    "Peanut butter or peanut paste",
    "Pear, canned in light syrup, not drained",
    "Persimmon, pulp, raw",
    "Pine nuts",
    "Pineapple, in light syrup, canned, drained",
    "Pomegranate, pulp and pips, raw",
    "Radish, raw",
    "Red cabbage, raw",
    "Red kuri squash, pulp, raw",
    "Rosemary, fresh",
    "Snow pea, boiled/cooked in water",
    "Soy \"cream\" preparation",
    "Spinach, raw",
    "Spring vegetables, frozen, raw (French beans, carrots, potatoes, green peas, onions)",
    "Sweet corn, canned, drained",
    "Sweet pepper, green, cooked",
    "Sweet potato, raw",
    "Swiss chard, raw",
    "Tomato, cherry, raw",
    "Tomato, dried",
    "Tomato, raw",
    "Watermelon, pulp, raw"
  ],
  "Dairy Products": [
    "Aioli sauce (garlic and olive oil mayonnaise), prepacked",
    "Apple pie with custard (flour, eggs, cream, sugar, apple alcohol)",
    "Baklava (oriental pastry with almonds and syrup)",
    "Brioche",
    "Butter biscuit (cookie)",
    "Caramelized custard cream (crème brûlée), refrigerated",
    "Cheese sauce for risotto or pasta, prepacked",
    "Christmas brioche with candied fruits, prepacked",
    "Cream sauce",
    "Cream sauce with mushrooms, prepacked",
    "Custard dessert, coffee, refrigerated",
    "Dark chocolate bar, filled with praline",
    "Doughnut, plain",
    "Grand veneur sauce (a reduction of red wine with garlic, shallots and red currant jelly), prepacked",
    "Gruyere cheese, France, Protected Geographical Indication, from cow's milk",
    "Light custard cream with vanilla, prepacked",
    "Liquid cream 30% fat, UHT",
    "Maasdam-type cheese, reduced fat",
    "Macaroon",
    "Meal replacement low calorie, in powder, reconstituted with skimmed milk, milkshake type",
    "Meringue",
    "Milk roll filled with chocolate drops, prepacked",
    "Milk roll, from bakery",
    "Mineral sparkling water (Arcens), bottled, averagely mineralized",
    "Olive oil, extra virgin",
    "Riste (Eggplant, tomatoes, onions)",
    "Rosemary, dried",
    "Soy sauce, prepacked",
    "Thyme, dried",
    "Walnut, dried, husked",
    "Yogurt cake",
    "Yogurt, goat's milk, plain, around 5% fat"
  ]
}