# Generated by Django 5.1.3 on 2024-12-24 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Companys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Providers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("providers_name", models.CharField(max_length=255, unique=True)),
                ("phone_number", models.CharField(max_length=15)),
                ("website_link", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Total_CO2e",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comp", models.IntegerField()),
                ("scope", models.IntegerField()),
                ("subcategory", models.FloatField()),
                ("year", models.IntegerField()),
                ("total_co2e", models.FloatField()),
                ("gas1", models.FloatField()),
                ("gas2", models.FloatField()),
                ("gas3", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Plans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_name", models.CharField(max_length=100)),
                ("carbon_cost", models.FloatField()),
                ("total_cost", models.FloatField()),
                ("peak_cost", models.FloatField(blank=True, null=True)),
                ("off_peak_cost", models.FloatField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="yearly_steps.providers",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScopeSteps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("quarter", models.IntegerField()),
                ("scope_type", models.IntegerField()),
                ("description", models.TextField()),
                ("difficulty", models.IntegerField()),
                ("transition_percentage", models.FloatField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="yearly_steps.companys",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="yearly_steps.plans",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScopeTotals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope_1_total", models.FloatField()),
                ("scope_2_total", models.FloatField()),
                ("scope_3_total", models.FloatField()),
                ("scope_total", models.FloatField()),
                ("scope_1_target", models.FloatField()),
                ("scope_2_target", models.FloatField()),
                ("scope_3_target", models.FloatField()),
                ("target_timeframe", models.IntegerField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="yearly_steps.companys",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShoppingCartContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="yearly_steps.companys",
                    ),
                ),
                (
                    "scope_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="yearly_steps.scopesteps",
                    ),
                ),
            ],
            options={
                "db_table": "shopping_cart_content",
                "managed": True,
            },
        ),
    ]
