# Generated by Django 5.1.3 on 2024-11-20 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScopeStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope_type", models.CharField(max_length=20)),
                ("description", models.TextField()),
                ("difficulty", models.CharField(max_length=50)),
                ("savings", models.FloatField()),
                ("emissions_savings", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recommended_plan", models.TextField(blank=True, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("carbon_emission_savings", models.FloatField(blank=True, null=True)),
                ("cost_savings", models.FloatField(blank=True, null=True)),
                ("peak_cost", models.FloatField(blank=True, null=True)),
                ("off_peak_cost", models.FloatField(blank=True, null=True)),
                (
                    "scope_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="yearly_steps.scopestep",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScopeTotal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope_1_total", models.FloatField()),
                ("scope_2_total", models.FloatField()),
                ("scope_3_total", models.FloatField()),
                ("scope_total", models.FloatField()),
                ("scope_1_target", models.FloatField()),
                ("scope_2_target", models.FloatField()),
                ("scope_3_target", models.FloatField()),
                ("target_timeframe", models.CharField(max_length=100)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="yearly_steps.company",
                        to_field="company_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="YearlyStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("quarter", models.IntegerField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="yearly_steps.company",
                        to_field="company_id",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="scopestep",
            name="yearly_step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="yearly_steps.yearlystep",
            ),
        ),
    ]
