# Generated by Django 5.1.3 on 2025-01-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yearly_steps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plans",
            name="data",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
