# Generated by Django 5.1.4 on 2025-01-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yearly_steps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plans",
            name="data",
            field=models.TextField(default="No data is provided", null=True),
        ),
    ]
