# Generated by Django 5.1.3 on 2024-11-21 17:51

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yearly_steps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScopeVector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("quarter", models.IntegerField()),
                ("scope_name", models.CharField(max_length=20)),
                ("vector", pgvector.django.vector.VectorField(dimensions=6)),
            ],
            options={
                "db_table": "scope_vector",
            },
        ),
    ]
