# Generated by Django 5.1.4 on 2024-12-12 13:43

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearly_steps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VectorTotalCO2e',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2e_vector', pgvector.django.vector.VectorField(dimensions=4)),
                ('total_co2e', models.ForeignKey(db_column='parent_id', on_delete=django.db.models.deletion.CASCADE, to='yearly_steps.total_co2e')),
            ],
            options={
                'db_table': 'vector_total_co2e',
                'managed': True,
            },
        ),
    ]
