# Generated by Django 5.1.3 on 2024-12-13 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yearly_steps", "0002_remove_recommendations_provider_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recommendations",
            old_name="provider",
            new_name="providers",
        ),
    ]
