# Generated by Django 5.1.2 on 2025-01-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yearly_steps', '0002_alter_plans_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcartcontent',
            options={},
        ),
        migrations.RemoveField(
            model_name='companys',
            name='company_id',
        ),
        migrations.AlterField(
            model_name='companys',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plans',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='providers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scopesteps',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scopetotals',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shoppingcartcontent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='total_co2e',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='shoppingcartcontent',
            table=None,
        ),
    ]
