# Generated by Django 5.1.3 on 2024-11-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yearly_steps", "0002_scopevector"),
    ]

    operations = [
        migrations.CreateModel(
            name="Total_CO2e",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField(unique=True)),
                ("scope", models.IntegerField()),
                ("subcategory", models.FloatField()),
                ("year", models.IntegerField()),
                ("total_co2e", models.FloatField()),
            ],
        ),
    ]
