# Generated by Django 5.1.3 on 2024-12-13 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yearly_steps", "0003_rename_provider_recommendations_providers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shoppingcartcontent",
            name="co2savings",
        ),
        migrations.RemoveField(
            model_name="shoppingcartcontent",
            name="costSavings",
        ),
        migrations.RemoveField(
            model_name="shoppingcartcontent",
            name="name",
        ),
        migrations.RemoveField(
            model_name="shoppingcartcontent",
            name="transition",
        ),
        migrations.AddField(
            model_name="shoppingcartcontent",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="yearly_steps.providerinfo",
            ),
        ),
    ]
