# Generated by Django 5.1.2 on 2025-01-25 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearly_steps', '0003_alter_shoppingcartcontent_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companys',
            old_name='id',
            new_name='company_id',
        ),
    ]
