# Generated by Django 5.1.3 on 2024-11-28 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yearly_steps", "0003_total_co2e"),
    ]

    operations = [
        migrations.RenameField(
            model_name="total_co2e",
            old_name="company_id",
            new_name="company",
        ),
    ]
