# Generated by Django 5.1.2 on 2025-01-25 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearly_steps', '0004_rename_id_companys_company_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shoppingcartcontent',
            table='yearly_steps_shoppingcartcontent',
        ),
    ]
