# Generated by Django 5.1.3 on 2024-11-28 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yearly_steps", "0004_rename_company_id_total_co2e_company"),
    ]

    operations = [
        migrations.RenameField(
            model_name="total_co2e",
            old_name="company",
            new_name="companys",
        ),
    ]
