# Generated by Django 5.1.2 on 2025-01-25 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearly_steps', '0005_alter_shoppingcartcontent_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shoppingcartcontent',
            table=None,
        ),
    ]
