# Generated by Django 5.1.3 on 2024-11-28 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yearly_steps", "0005_rename_company_total_co2e_companys"),
    ]

    operations = [
        migrations.RenameField(
            model_name="total_co2e",
            old_name="companys",
            new_name="comp",
        ),
    ]
