# Generated by Django 5.1.3 on 2024-12-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yearly_steps", "0007_alter_total_co2e_comp"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingCartContents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField()),
                ("year", models.IntegerField()),
                ("quarter", models.IntegerField()),
                ("scope", models.IntegerField()),
                ("transition", models.FloatField()),
                ("scope_type", models.CharField()),
                ("difficulty", models.IntegerField()),
                ("savings", models.FloatField()),
                ("emissions_savings", models.FloatField()),
                ("recommended_plan", models.TextField()),
            ],
            options={
                "db_table": "ShoppingCartContents",
                "managed": True,
            },
        ),
    ]
