# Generated by Django 5.1.3 on 2024-12-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yearly_steps", "0007_alter_total_co2e_comp"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingCartContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField(default=1)),
                ("name", models.TextField()),
                ("transition", models.FloatField()),
                ("costSavings", models.FloatField()),
                ("co2savings", models.FloatField()),
            ],
            options={
                "db_table": "ShoppingCartContent",
                "managed": True,
            },
        ),
    ]
