# Generated by Django 5.1.3 on 2024-12-03 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yearly_steps', '0007_alter_total_co2e_comp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScopeVector',
        ),
    ]
