# Generated by Django 5.1.3 on 2024-12-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yearly_steps", "0008_shoppingcartcontent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Total_CO2e",
        ),
    ]
