# Generated by Django 5.1.3 on 2024-12-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yearly_steps", "0009_delete_total_co2e"),
    ]

    operations = [
        migrations.CreateModel(
            name="Total_CO2e",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comp", models.IntegerField()),
                ("scope", models.IntegerField()),
                ("subcategory", models.FloatField()),
                ("year", models.IntegerField()),
                ("total_co2e", models.FloatField()),
                ("gas1", models.FloatField()),
                ("gas2", models.FloatField()),
                ("gas3", models.FloatField()),
            ],
        ),
    ]
