# -*- coding: utf-8 -*-
"""LCUSector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mba8n3ztS51sf6E9pl3jRgBiPWl8RzY6
"""

class LCUSector:
    def __init__(self, B19SVUSpeak_usage, B19SVUSpartpeak_usage, B19SVUSoffpeak_usage,
                 B19SVUWpeak_usage,B19SVUWsuperoffpeak_usage,B19SVUWoffpeak_usage,Summer_highest_usage_B19SV,Winter_highest_usage_B19SV,
                 B19PVUSpeak_usage,B19PVUSpartpeak_usage,B19PVUSoffpeak_usage,
                 B19PVUWpeak_usage,B19PVUWsuperoffpeak_usage,B19PVUWoffpeak_usage,Summer_highest_usage_B19PV,Winter_highest_usage_B19PV,
                 B19TVUSpeak_usage,B19TVUSpartpeak_usage,B19TVUSoffpeak_usage,
                 B19TVUWpeak_usage,B19TVUWsuperoffpeak_usage,B19TVUWoffpeak_usage,Summer_highest_usage_B19TV,Winter_highest_usage_B19TV,
                 B20SVUSpeak_usage, B20SVUSpartpeak_usage, B20SVUSoffpeak_usage,
                 B20SVUWpeak_usage,B20SVUWsuperoffpeak_usage,B20SVUWoffpeak_usage,Summer_highest_usage_B20SV,Winter_highest_usage_B20SV,
                 B20PVUSpeak_usage,B20PVUSpartpeak_usage,B20PVUSoffpeak_usage,
                 B20PVUWpeak_usage,B20PVUWsuperoffpeak_usage,B20PVUWoffpeak_usage,Summer_highest_usage_B20PV,Winter_highest_usage_B20PV,
                 B20TVUSpeak_usage,B20TVUSpartpeak_usage,B20TVUSoffpeak_usage,
                 B20TVUWpeak_usage,B20TVUWsuperoffpeak_usage,B20TVUWoffpeak_usage,Summer_highest_usage_B20TV,Winter_highest_usage_B20TV,
                 meter_input,time_in_use,max_15min_usage):
        self.B19SVUSpeak_usage = B19SVUSpeak_usage
        self.B19SVUSpartpeak_usage = B19SVUSpartpeak_usage
        self.B19SVUSoffpeak_usage = B19SVUSoffpeak_usage
        self.B19SVUWpeak_usage = B19SVUWpeak_usage
        self.B19SVUWsuperoffpeak_usage = B19SVUWsuperoffpeak_usage
        self.B19SVUWoffpeak_usage = B19SVUWoffpeak_usage
        self.Summer_highest_usage_B19SV = Summer_highest_usage_B19SV
        self.Winter_highest_usage_B19SV = Winter_highest_usage_B19SV
        self.B19PVUSpeak_usage = B19PVUSpeak_usage
        self.B19PVUSpartpeak_usage = B19PVUSpartpeak_usage
        self.B19PVUSoffpeak_usage = B19PVUSoffpeak_usage
        self.B19PVUWpeak_usage = B19PVUWpeak_usage
        self.B19PVUWsuperoffpeak_usage = B19PVUWsuperoffpeak_usage
        self.B19PVUWoffpeak_usage = B19PVUWoffpeak_usage
        self.Summer_highest_usage_B19PV = Summer_highest_usage_B19PV
        self.Winter_highest_usage_B19PV = Winter_highest_usage_B19PV
        self.B19TVUSpeak_usage = B19TVUSpeak_usage
        self.B19TVUSpartpeak_usage = B19TVUSpartpeak_usage
        self.B19TVUSoffpeak_usage = B19TVUSoffpeak_usage
        self.B19TVUWpeak_usage = B19TVUWpeak_usage
        self.B19TVUWsuperoffpeak_usage = B19TVUWsuperoffpeak_usage
        self.B19TVUWoffpeak_usage = B19TVUWoffpeak_usage
        self.Summer_highest_usage_B19TV = Summer_highest_usage_B19TV
        self.Winter_highest_usage_B19TV = Winter_highest_usage_B19TV
        self.B20SVUSpeak_usage = B20SVUSpeak_usage
        self.B20SVUSpartpeak_usage = B20SVUSpartpeak_usage
        self.B20SVUSoffpeak_usage = B20SVUSoffpeak_usage
        self.B20SVUWpeak_usage = B20SVUWpeak_usage
        self.B20SVUWsuperoffpeak_usage = B20SVUWsuperoffpeak_usage
        self.B20SVUWoffpeak_usage = B20SVUWoffpeak_usage
        self.Summer_highest_usage_B20SV = Summer_highest_usage_B20SV
        self.Winter_highest_usage_B20SV = Winter_highest_usage_B20SV
        self.B20PVUSpeak_usage = B20PVUSpeak_usage
        self.B20PVUSpartpeak_usage = B20PVUSpartpeak_usage
        self.B20PVUSoffpeak_usage = B20PVUSoffpeak_usage
        self.B20PVUWpeak_usage = B20PVUWpeak_usage
        self.B20PVUWsuperoffpeak_usage = B20PVUWsuperoffpeak_usage
        self.B20PVUWoffpeak_usage = B20PVUWoffpeak_usage
        self.Summer_highest_usage_B20PV = Summer_highest_usage_B20PV
        self.Winter_highest_usage_B20PV = Winter_highest_usage_B20PV
        self.B20TVUSpeak_usage = B20TVUSpeak_usage
        self.B20TVUSpartpeak_usage = B20TVUSpartpeak_usage
        self.B20TVUSoffpeak_usage = B20TVUSoffpeak_usage
        self.B20TVUWpeak_usage = B20TVUWpeak_usage
        self.B20TVUWsuperoffpeak_usage = B20TVUWsuperoffpeak_usage
        self.B20TVUWoffpeak_usage = B20TVUWoffpeak_usage
        self.Summer_highest_usage_B20TV = Summer_highest_usage_B20TV
        self.Winter_highest_usage_B20TV = Winter_highest_usage_B20TV
        self.meter_input = meter_input
        self.time_in_use = time_in_use
        self.max_15min_usage = max_15min_usage