# -*- coding: utf-8 -*-
"""SMUSector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Va1NjMDqAxny9SmY2yMU9ZPrJCkJ9T66
"""

class SMUSector:
    def __init__(self, A1NTUStotal_usage, A1NTUWtotal_usage, A1USpeak_usage,
                 A1USpartpeak_usage, A1USoffpeak_usage, A1UWpartpeak_usage,
                 A1UWoffpeak_usage, B1USpeak_usage, B1USpartpeak_usage, B1USoffpeak_usage,
                 B1UWpeak_usage, B1UWsuperoffpeak_usage, B1UWoffpeak_usage,
                 B1STUSpeak_usage, B1STUSpartpeak_usage, B1STUSoffpeak_usage,
                 B1STUWpeak_usage, B1STUWpartpeak_usage, B1STUWsuperoffpeak_usage,
                 B1STUWoffpeak_usage, B6USpeak_usage, B6USoffpeak_usage,
                 B6UWpeak_usage, B6UWsuperoffpeak_usage,B6UWoffpeak_usage,
                 B10SVUSpeak_usage,B10SVUSpartpeak_usage,B10SVUSoffpeak_usage,
                 B10SVUWpeak_usage, B10SVUWsuperoffpeak_usage, B10SVUWoffpeak_usage,
                 B10PVUSpeak_usage,B10PVUSpartpeak_usage,B10PVUSoffpeak_usage,
                 B10PVUWpeak_usage,B10PVUWsuperoffpeak_usage,B10PVUWoffpeak_usage,
                 B10TVUSpeak_usage, B10TVUSpartpeak_usage,B10TVUSoffpeak_usage,
                 B10TVUWpeak_usage,B10TVUWsuperoffpeak_usage, B10TVUWoffpeak_usage,
                 meter_input,time_in_use, max_15min_usage,B1STU_highest_demand_15mins):
        self.A1NTUStotal_usage = A1NTUStotal_usage
        self.A1NTUWtotal_usage = A1NTUWtotal_usage
        self.A1USpeak_usage = A1USpeak_usage
        self.A1USpartpeak_usage = A1USpartpeak_usage
        self.A1USoffpeak_usage = A1USoffpeak_usage
        self.A1UWpartpeak_usage = A1UWpartpeak_usage
        self.A1UWoffpeak_usage = A1UWoffpeak_usage
        self.B1USpeak_usage = B1USpeak_usage
        self.B1USpartpeak_usage = B1USpartpeak_usage
        self.B1USoffpeak_usage = B1USoffpeak_usage
        self.B1UWpeak_usage = B1UWpeak_usage
        self.B1UWsuperoffpeak_usage = B1UWsuperoffpeak_usage
        self.B1UWoffpeak_usage = B1UWoffpeak_usage
        self.B1UTBSpeak_usage = B1STUSpeak_usage
        self.B1STUSpartpeak_usage = B1STUSpartpeak_usage
        self.B1STUSoffpeak_usage = B1STUSoffpeak_usage
        self.B1STUWpeak_usage = B1STUWpeak_usage
        self.B1STUWpartpeak_usage = B1STUWpartpeak_usage
        self.B1STUWsuperoffpeak_usage = B1STUWsuperoffpeak_usage
        self.B1STUWoffpeak_usage = B1STUWoffpeak_usage
        self.B6USpeak_usage = B6USpeak_usage
        self.B6USoffpeak_usage = B6USoffpeak_usage
        self.B6UWpeak_usage = B6UWpeak_usage
        self.B6UWsuperoffpeak_usage = B6UWsuperoffpeak_usage
        self.B6UWoffpeak_usage = B6UWoffpeak_usage
        self.B10SVUSpeak_usage = B10SVUSpeak_usage
        self.B10SVUSpartpeak_usage = B10SVUSpartpeak_usage
        self.B10SVUSoffpeak_usage = B10SVUSoffpeak_usage
        self.B10SVUWpeak_usage = B10SVUWpeak_usage
        self.B10SVUWsuperoffpeak_usage = B10SVUWsuperoffpeak_usage
        self.B10SVUWoffpeak_usage = B10SVUWoffpeak_usage
        self.B10PVUSpeak_usage = B10PVUSpeak_usage
        self.B10PVUSpartpeak_usage = B10PVUSpartpeak_usage
        self.B10PVUSoffpeak_usage = B10PVUSoffpeak_usage
        self.B10PVUWpeak_usage = B10PVUWpeak_usage
        self.B10PVUWsuperoffpeak_usage = B10PVUWsuperoffpeak_usage
        self.B10PVUWoffpeak_usage = B10PVUWoffpeak_usage
        self.B10TVUSpeak_usage = B10TVUSpeak_usage
        self.B10TVUSpartpeak_usage = B10TVUSpartpeak_usage
        self.B10TVUSoffpeak_usage = B10TVUSoffpeak_usage
        self.B10TVUWpeak_usage = B10TVUWpeak_usage
        self.B10TVUWsuperoffpeak_usage = B10TVUWsuperoffpeak_usage
        self.B10TVUWoffpeak_usage = B10TVUWoffpeak_usage
        self.meter_input = meter_input
        self.time_in_use = time_in_use
        self.max_15min_usage = max_15min_usage
        self.B1STU_highest_demand_15mins = B1STU_highest_demand_15mins

