from enum import Enum

class DecarbStepType(Enum):
    FLIGHTS = 3
    FLIGHTS_RETURN = 4
    COMMUTING_INDIVIDUAL = 1
    COMMUTING_CARPOOL  =2
    ELECTRICITY = 5

DecarbStepType = Enum('DecarbStepType', ['COMMUTING_INDIVIDUAL', 'COMMUTING_CARPOOL','FLIGHTS','FLIGHTS_RETURN', 'ELECTRICITY'])
