from enum import Enum

class DecarbStepType(str,Enum):
    
    COMMUTING_INDIVIDUAL = "COMMUTING_INDIVIDUAL"
    COMMUTING_CARPOOL = "COMMUTING_CARPOOL"
    FLIGHTS = "FLIGHTS"
    FLIGHTS_RETURN = "FLIGHTS_RETURN"
    EMISSIONS_FLIGHTS = "EMISSIONS_FLIGHTS"
    ELECTRICITY = "ELECTRICITY"
    CRU = "CRU"

    def __str__(self) -> str:
        return str.__str__(self)

DecarbStepType = Enum('DecarbStepType', ['COMMUTING_INDIVIDUAL', 'COMMUTING_CARPOOL','FLIGHTS','FLIGHTS_RETURN','EMISSIONS_FLIGHTS','ELECTRICITY', 'CRU'])
