# -*- coding: utf-8 -*-
"""Electricity Work

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ePwPoGLE4I2v2nhUDYOAZqynoNYGu0vv
"""

import pandas as pd

from components.electricity.optimization_calculation.lcbelectricityrateplan import LCBElectricityRatePlan
from components.electricity.optimization_calculation.lcuelectricityrateplan import LCUElectricityRatePlan
from components.electricity.optimization_calculation.smuelectricityrateplan import SMUElectricityRatePlan
from components.electricity.optimization_calculation.smbelectricityrateplan import SMBElectricityRatePlan
from components.electricity.sectors.lcbsector import LCBSector
from components.electricity.sectors.lcbsector import LCBSector_simplified
from components.electricity.sectors.lcusector import LCUSector
from components.electricity.sectors.lcusector import LCUSector_simplified
from components.electricity.sectors.smbsector import SMBSector
from components.electricity.sectors.smbsector import SMBSector_simplified
from components.electricity.sectors.smusector import SMUSector
from components.electricity.sectors.smusector import SMUSector_simplified

class ElectricityWork:
    def __init__(self, file_path, user_zip_code,lcb_sector, smb_sector, lcu_sector, smu_sector):
        self.file_path = file_path
        self.sheets = pd.read_excel(self.file_path, sheet_name=None)
        self.pge_service_df = self.sheets['PG&E Service Area']
        self.cca_df = self.sheets['CCA']
        self.joint_rate_plan_df = self.sheets['Joint Rate Plan']
        self.bundled_peak_time_price_df = self.sheets['Bundled Peak Time Price']
        self.unbundled_peak_time_price_df = self.sheets['Unbundled Peak Time Price']
        self.user_zip_code = user_zip_code

        self.lcb_sector = lcb_sector
        self.smb_sector = smb_sector
        self.lcu_sector = lcu_sector
        self.smu_sector = smu_sector

    def check_zip_code(self, user_zip_code):
        if user_zip_code in self.pge_service_df['PG&E Service area Zip Code'].values:
            return "In PG&E service"
        else:
            return "Not in PG&E service"

    def match_cca_service(self, user_zip_code):
        for column in self.cca_df.columns:
            if user_zip_code in self.cca_df[column].values:
                return f"Matched in CCA: {column}"
        return "No CCA"

    def get_matched_rows(self, user_zip_code, user_sector, user_bundled):
        result1 = self.check_zip_code(user_zip_code)
        result2 = self.match_cca_service(user_zip_code)

        if "Matched in CCA" in result2:
            matched_column = result2.split(": ")[1]
            location_matched_rows = self.joint_rate_plan_df[self.joint_rate_plan_df['Location'] == matched_column]
            final_matched_rows = location_matched_rows[location_matched_rows['Sector'] == user_sector]
            return final_matched_rows
        elif "No CCA" in result2:
            if user_bundled == "Yes":
                sector_matched_rows = self.bundled_peak_time_price_df[self.bundled_peak_time_price_df['Sector'] == user_sector]
            else:
                sector_matched_rows = self.unbundled_peak_time_price_df[self.unbundled_peak_time_price_df['Sector'] == user_sector]
            return sector_matched_rows
        else:
            return "No matching rows in joint rate plan", "No matching rows in joint rate comparison"

    def create_smb_sector(self, user_input_peak_usage, user_input_part_peak_usage, user_input_super_off_peak_usage, user_input_off_peak_usage,meter_input,time_in_use,max_15min_usage, user_sector,user_B1STB_highest_demand_15mins):
        smb_sector = SMBSector_simplified(user_input_peak_usage, user_input_part_peak_usage, user_input_super_off_peak_usage, user_input_off_peak_usage,meter_input,time_in_use,max_15min_usage, user_sector,user_B1STB_highest_demand_15mins)
        return smb_sector

    def create_lcb_sector(self, user_input_peak_usage, user_input_part_peak_usage, user_input_super_off_peak_usage, user_input_off_peak_usage, user_electricity_bill_season,
                 meter_input,time_in_use,max_15min_usage, user_sector, user_current_plan):
        lcb_sector = LCBSector_simplified(user_input_peak_usage, user_input_part_peak_usage, user_input_super_off_peak_usage, user_input_off_peak_usage, user_electricity_bill_season,
                 meter_input,time_in_use,max_15min_usage, user_sector, user_current_plan)
        return lcb_sector

    def create_smu_sector(self, user_input_peak_usage, user_input_part_peak_usage, user_input_super_off_peak_usage, user_input_off_peak_usage,meter_input,time_in_use,max_15min_usage, user_sector,user_B1STU_highest_demand_15mins):
        smu_sector= SMUSector_simplified(user_input_peak_usage, user_input_part_peak_usage, user_input_super_off_peak_usage, user_input_off_peak_usage,meter_input,time_in_use,max_15min_usage, user_sector,user_B1STU_highest_demand_15mins)
        return smu_sector

    def create_lcu_sector(self, user_input_peak_usage, user_input_part_peak_usage, user_input_super_off_peak_usage, user_input_off_peak_usage, user_electricity_bill_season,
                 meter_input,time_in_use,max_15min_usage, user_sector, user_current_plan):
        lcu_sector = LCUSector_simplified(user_input_peak_usage, user_input_part_peak_usage, user_input_super_off_peak_usage, user_input_off_peak_usage, user_electricity_bill_season,
                 meter_input,time_in_use,max_15min_usage, user_sector, user_current_plan)
        return lcu_sector
    
    def get_result(self, result, keys):
        number_result = result['x']
        optimal_solution_value = result['objective']
        optimal_plan_name = {name for i, name in enumerate(keys) if result['x'][i] == 1}
        return (number_result, optimal_solution_value, optimal_plan_name)
    
    def print_plan(self,optimal_result):
        optimal_solution_name=optimal_result[2]
        print(optimal_solution_name)
        
    def check_condition_and_run(self, user_sector, user_bundled):
        condition1 = (user_sector == 'Large Commercial and Industrial' and user_bundled == 'Yes')
        condition2 = (user_sector == 'Large Commercial and Industrial' and user_bundled == 'No')
        condition3 = (user_sector == 'Small and Medium Business' and user_bundled == 'Yes')
        condition4 = (user_sector == 'Small and Medium Business' and user_bundled == 'No')

        rate_plan = None 
        keys = []
        if condition1:
            rate_plan = LCBElectricityRatePlan(self.file_path, 'Bundled Peak Time Price', self.lcb_sector)
            keys = ['B19SVB', 'B19PVB', 'B19TVB', 'B19B', 'B20SVB', 'B20PVB', 'B20TVB', 'B20B']            
        elif condition2:
            rate_plan = LCUElectricityRatePlan(self.file_path, 'Unbundled Peak Time Price', self.lcu_sector)
            keys = ['B19SVU', 'B19PVU', 'B19TVU', 'B19U', 'B20SVU', 'B20PVU', 'B20TVU', 'B20U']
        elif condition3:
            rate_plan = SMBElectricityRatePlan(self.file_path, 'Bundled Peak Time Price', self.smb_sector)
            keys = ['A1NTB', 'A1B', 'B1B', 'B1STB', 'B6B', 'B10SVB', 'B10PVB', 'B10TVB', 'A1NTB_poly', 'A1NTB_single', 'A1B_poly', 'A1B_single', 'B1B_poly', 'B1B_single', 'B1STB_poly', 'B1STB_single', 'B6B_poly', 'B6B_single']
        elif condition4:
            rate_plan = SMUElectricityRatePlan(self.file_path, 'Unbundled Peak Time Price', self.smu_sector)
            keys = ['A1NTU', 'A1U', 'B1U', 'B1STU', 'B6U', 'B10SVU', 'B10PVU', 'B10TVU', 'A1NTU_poly', 'A1NTU_single', 'A1U_poly', 'A1U_single', 'B1U_poly', 'B1U_single', 'B1STU_poly', 'B1STU_single', 'B6U_poly', 'B6U_single']
        else:
            err_msg = "check_condition_and_run: Condition not met, not running the script."
            print(err_msg)
            raise Exception(err_msg)
        
        result = rate_plan.optimize()
        optimal_solution_result=self.get_result(result, keys)
        return optimal_solution_result
